DSD-1546: UI updates
NYPL/nypl-header-app pull request #23
Opened 2023-08-17 20:54 UTC by EdwinGuzman

Fixes [JIRA ticket xxx](http://jira.nypl.org/browse/DSD-XXX)

## This PR does the following:

-

## How has this been tested?

### Checklist:

- [ ] I have updated the Readme documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2023-08-21 18:52 UTC, EdwinGuzman commented
@bigfishdesign13 not completely ready yet but can you do a first pass to check it out?

The new mobile designs for the button nav is not full height (from what I understand in the figma file) so the active state looks off; new on the left and prod on the right:
<img width="504" alt="Screen Shot 2023-08-21 at 2 51 23 PM" src="https://github.com/NYPL/nypl-header-app/assets/1280564/286427a1-e30e-45cc-bb8b-c4b7f07d6428">

2023-08-21 21:03 UTC, bigfishdesign13 reviewed
Looks good.  Still a work in progress, of course.  I left a few comments about spacing and font sizes.

2023-08-21 21:03 UTC, bigfishdesign13 commented on src/theme/headerLowerNav.ts
> +      marginEnd: { lg: "s", xl: "m" },
In the browser, I am seeing this go to `xs` for the breakpoint just above the mobile view.  And that is a bit too small.  Where is that coming from?  I bumped it up to `s` and it still seems to fit.

2023-08-21 21:03 UTC, bigfishdesign13 commented on src/theme/headerUpperNav.ts
>        color: "ui.black",
You many need to add something to override this for the `Donate` link button.

2023-08-21 21:07 UTC, bigfishdesign13 commented on src/theme/headerLowerNav.ts
> +      fontSize: "desktop.subtitle.subtitle2",
This comment didn't make it into my review.  Maybe I didn't hit the submit button?  Hmm, not sure.

This should be `subtitle1` for the largest breakpoint.

2023-08-22 16:59 UTC, EdwinGuzman commented on src/theme/headerUpperNav.ts
>        color: "ui.black",
The `Donate` link button already renders as white unless if you mean something else?

2023-08-22 17:07 UTC, EdwinGuzman commented
@bigfishdesign13 ready for a review

2023-08-23 14:37 UTC, bigfishdesign13 commented on src/theme/headerUpperNav.ts
>        color: "ui.black",
I am seeing black button text.

![image](https://github.com/NYPL/nypl-header-app/assets/5241828/296d6707-7c6e-4c71-8e9c-18853472abeb)

2023-08-23 15:04 UTC, EdwinGuzman commented on src/theme/headerUpperNav.ts
>        color: "ui.black",
Yeah, it's white for me. I wonder if the value somehow got cached _in my browser_? That's not good, but I'll make the color explicit.

2023-08-23 15:04 UTC, EdwinGuzman commented on src/theme/headerUpperNav.ts
>        color: "ui.black",
(I do see it as black in an incognito window.

2023-08-23 15:20 UTC, bigfishdesign13 requested changes
Overall, looks great.  I left one comment about the spacing between the links in the bottom nav.  

I also think it would be good to adjust the padding on the `My Account` and `Search` links (yes, I know they are actually buttons) to make the focus rectangle the same size as the other links.  What do you think?

2023-08-23 15:20 UTC, bigfishdesign13 commented on src/theme/headerLowerNav.ts
> +      marginEnd: { lh: "s", xl: "m" },
The code you have here looks correct, but in the browser I am seeing the spacing between the links in the lower nav set to 8px (xs) from the 832px-1023px.

2023-08-23 15:56 UTC, EdwinGuzman commented
> I also think it would be good to adjust the padding on the My Account and Search links (yes, I know they are actually buttons) to make the focus rectangle the same size as the other links. What do you think?

I like this idea but when you click on them, the background color changes and we'd have to update this as well. It's not the padding in the button but rather the min-height and min-width. Here's an example: 
<img width="306" alt="Screen Shot 2023-08-23 at 11 56 00 AM" src="https://github.com/NYPL/nypl-header-app/assets/1280564/24ec779c-5aff-4e1c-afbf-d1d473116d37">

If only the height/width is updated on the non-active or non-focus state, then the navs jump around.

2023-08-23 16:02 UTC, EdwinGuzman commented
Updated

2023-08-24 21:06 UTC, bigfishdesign13 commented
@EdwinGuzman 
Some comments came up when I was discussing the `Header` with the designers.
- For desktop, the bottom nav looks like it could be pushed down a bit further so the bottom of the bottom nav is in better alignment with the bottom of the logo.
- The links for `My Account` and `Search` are using Arial font family.
- The sizing of the icons in the mobile menu is not great.  I am going to update some icons and add some new ones to use.

2023-08-25 15:06 UTC, EdwinGuzman commented
Did the first two bullet point updates but will need to wait for the new icons.

2023-08-31 21:15 UTC, EdwinGuzman commented
Updated with new icons and DS v1.7.2!

2023-09-06 16:23 UTC, bigfishdesign13 commented
@EdwinGuzman 
The vertical alignment of the `My Account`, `Search` and `hamburger` icons needs to be adjusted in order to better align with the vertical alignment of the `Locations` icon.  Add the following styles to the `<button>` wrappers for those icons.

```
display: flex;
justify-content: center;
```

2023-09-06 17:43 UTC, EdwinGuzman commented
Updated.

2023-09-06 18:37 UTC, bigfishdesign13 approved these changes
Looks good!

2023-09-11 13:46 UTC, merged